title: "Mugtaba Awad Portfolio"
description: "Business Intelligence | Data Analytics | Data Science Projects"
theme: jekyll-theme-minimal
markdown: kramdown
show_downloads: false

include:
index.md
about.md
work.md
projects.md
contact.md
  - assets
  - projects

permalink: pretty
